### ISSUE TITLE
User Session terminates and keeps being redirected to login page 

### ISSUE THREAD

**Issue by speng11** [speng11/ProjectHub#14]
When we click "Show" and "Edit" for Groups that are shown on the user dashboard once we've logged in, we get redirected to the login page and we are required to log in again.

**Comment by gtakhar** [comment]
Did you make sure you are always passing the token? If the token is not passed, you will automatically be logged out immediately.

**Comment by speng11** [comment]
Thank you for the tip! I'll make sure the pass the token
